[tools]
node = '22'
python = { version = "3.12", postinstall = "python -m pip install pipx" }
yarn = "4.11.0"

[tasks.migrate-sql]
run = 'node generate-migrations.ts'
dir = './scripts'
description = 'Use this to generate SQLite migrations'
