import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const stepsDir = path.join(here, '..', 'src', 'migrations', 'sqlite', 'steps');
const rawDir = path.join(stepsDir, 'raw');
const generatedDir = path.join(stepsDir, 'generated');

const AUTOGEN_HEADER = (name: string) => `// DO NOT EDIT: Generated by ${name} using \`mise migrate-sql\``;

function parseMigrationScript(scriptPath: string) {
    const content = fs.readFileSync(scriptPath, 'utf8').replace(/\r\n/g, '\n').trim();
    const checksum = crypto.createHash('sha256').update(content).digest('hex');
    const strVersion = path.basename(scriptPath).split('_')[0];
    const version = Number(strVersion);
    if (Number.isNaN(version)) {
        throw new Error(`Migration version is not numeric. Got: ${strVersion}`);
    }
    return { version, checksum, content, scriptPath };
}

function emitMigration(m: any) {
    return AUTOGEN_HEADER(`raw/${path.basename(m.scriptPath)}`)
        + '\nexport const migration = {\n'
        + `    version: ${m.version},\n`
        + `    checksum: ${JSON.stringify(m.checksum)},\n`
        + `    sql: ${JSON.stringify(m.content)},\n`
        + '};\n';
}

const migrations = fs.readdirSync(rawDir)
    .filter((file) => file.endsWith('.sql'))
    .map((file) => ({
        baseName: path.basename(file, '.sql'),
        ...parseMigrationScript(path.join(rawDir, file)),
    }))
    .sort((a, b) => a.version - b.version);

migrations.forEach((m, i) => {
    if (m.version !== i + 1) {
        throw new Error(
            `Migration versions must be sequential from 1; expected ${i + 1} but found ${m.version} (${m.baseName}).`
        );
    }
});

for (const m of migrations) {
    fs.writeFileSync(path.join(generatedDir, `${m.baseName}.ts`), emitMigration(m));
}

const imports = migrations
    .map((m, i) => `import { migration as m${i + 1} } from './${m.baseName}';`)
    .join('\n');
const list = migrations.map((_, i) => `m${i + 1}`).join(', ');

fs.writeFileSync(
    path.join(generatedDir, 'index.ts'),
    `${AUTOGEN_HEADER('generate-migrations.ts')}\n${imports}\n\nexport const MIGRATIONS = [${list}];\n`
);

console.log(`Generated ${migrations.length} migration(s) + index.`);
