import fs from "fs";
import path from "path";

import {FetchingJSONSchemaStore, InputData, JSONSchemaInput, quicktype} from "quicktype-core";

const REMOTE_SOURCE = {
    ecosystemDataUrl: "https://thunderstore.io/api/experimental/schema/dev/latest/",
    ecosystemJsonSchemaUrl: "https://thunderstore.io/api/experimental/schema/ecosystem-json-schema/latest/",
    gameImageBaseUrl: "https://gcdn.thunderstore.io/assets",
};
const LOCAL_SOURCE = {
    ecosystemDataUrl: "http://localhost:1337/latest.json",
    ecosystemJsonSchemaUrl: "http://localhost:1337/latest.schema.json",
    gameImageBaseUrl: "http://localhost:1337/assets",
};

const ECOSYSTEM_DATA_PATH = "./src/assets/data/ecosystem.json";
const ECOSYSTEM_JSON_SCHEMA_PATH = "./src/assets/data/ecosystemJsonSchema.json";
const ECOSYSTEM_DATA_TYPES_PATH = "./src/assets/data/ecosystemTypes.ts";
const GAME_IMAGE_DIR_PATH = "./public/images/game_selection";

/**
 * This script synchronizes the in-repo ecosystem schema JSON to the latest
 * version and generates matching TypeScript types.
 *
 * To only generate the TypeScript types without syncing with the
 * Thunderstore API, use `pnpm sync --types-only`
 */
async function updateSchema() {
    let schema: Buffer;

    const source = await isReachable("http://localhost:1337/healthz") ? LOCAL_SOURCE : REMOTE_SOURCE;
    if (process.argv.includes('--types-only')) {
        console.log("Skipping API update, reading JSON schema from disk...");
        schema = fs.readFileSync(ECOSYSTEM_JSON_SCHEMA_PATH);
        const data = Buffer.from(fs.readFileSync(ECOSYSTEM_DATA_PATH));
        console.log("Updating images...");
        await updateGameImages(data, source.gameImageBaseUrl);
    } else {
        console.log(`Syncing from ${new URL(source.ecosystemDataUrl).origin}...`);

        console.log("Updating ecosystem.json...");
        const response = await fetch(source.ecosystemDataUrl);
        if (response.status !== 200) {
            throw new Error(`Received non-200 status from schema API: ${response.status}`);
        }
        const data = Buffer.from(await response.arrayBuffer());
        fs.writeFileSync(ECOSYSTEM_DATA_PATH, data);

        await updateGameImages(data, source.gameImageBaseUrl);

        console.log("Updating ecosystemJsonSchema.json...");
        const schemaResponse = await fetch(source.ecosystemJsonSchemaUrl);
        if (schemaResponse.status !== 200) {
            throw new Error(`Received non-200 status from schema API: ${schemaResponse.status}`);
        }
        schema = Buffer.from(await schemaResponse.arrayBuffer());
        fs.writeFileSync(ECOSYSTEM_JSON_SCHEMA_PATH, schema);
    }

    console.log("Updating ecosystemTypes.ts...");
    const schemaInput = new JSONSchemaInput(new FetchingJSONSchemaStore());
    await schemaInput.addSource({name: "ThunderstoreEcosystem", schema: schema.toString()});
    const inputData = new InputData();
    inputData.addInput(schemaInput);
    const types = await quicktype({
        inputData,
        lang: "typescript",
        leadingComments: [{descriptionBlock: [
            "This file is automatically generated by the sync.ts script.",
            "Do not edit it manually.",
        ]}],
    });
    const finalTypes = enumKeysToUpperSnakeCase(types.lines.join("\n"));
    fs.writeFileSync(ECOSYSTEM_DATA_TYPES_PATH, finalTypes);
}

updateSchema();

async function updateGameImages(ecosystemData: Buffer, baseUrl: string): Promise<void> {
    const ecosystem = JSON.parse(ecosystemData.toString());
    const iconUrls = new Set<string>();
    for (const game of Object.values<any>(ecosystem.games ?? {})) {
        for (const entry of game?.r2modman ?? []) {
            const iconUrl = entry?.meta?.iconUrl;
            if (typeof iconUrl === "string" && iconUrl) {
                iconUrls.add(iconUrl);
            }
        }
    }

    console.log(`Updating ${iconUrls.size} game images...`);
    let failures = 0;
    for (const iconUrl of iconUrls) {
        try {
            await fetchGameImage(baseUrl, iconUrl);
        } catch (e) {
            console.warn(`  ${(e as Error).message}`);
            failures += 1;
        }
    }
    if (failures > 0) {
        console.warn(`Failed to fetch ${failures} of ${iconUrls.size} game images.`);
    }
}

async function isReachable(url: string): Promise<boolean> {
    try {
        await fetch(url);
        return true;
    } catch {
        return false;
    }
}

async function fetchGameImage(baseUrl: string, iconUrl: string): Promise<void> {
    const response = await fetch(`${baseUrl}/${iconUrl}`);
    if (response.status !== 200) {
        throw new Error(`Received non-200 status fetching ${iconUrl}: ${response.status}`);
    }
    const data = Buffer.from(await response.arrayBuffer());
    const outPath = path.join(GAME_IMAGE_DIR_PATH, iconUrl);
    fs.mkdirSync(path.dirname(outPath), {recursive: true});
    fs.writeFileSync(outPath, data);
}

function enumKeysToUpperSnakeCase(tsCode: string): string {
    const enumRegex = /export enum (\w+) \{([\s\S]*?)\}/g;
    const enumKeyValueRegex = /(\w+) = "(.*?)"/g;

    const enumKeyValueReplacer = (_: string, enumKey: string, enumValue: string) =>
        `${enumValue.replace(/-/g, "_").toUpperCase()} = "${enumValue}"`;

    return tsCode.replace(enumRegex, (_, enumName, enumBody) =>
        `export enum ${enumName} {${enumBody.replace(enumKeyValueRegex, enumKeyValueReplacer)}}`
    );
}
