name: Build Flatpak

on:
  workflow_dispatch:

jobs:
  build-flatpak:
    name: Build the Flatpak app
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-25.08
      options: --privileged
    steps:
      - uses: actions/checkout@v4

      - name: Build flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: r2modman.flatpak
          manifest-path: flatpak/io.github.ebkr.r2modman.yaml
